apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: person-service
build:
  artifacts:
    - image: piomin/person-service
      jib: {}
profiles:
  - name: v1
    deploy:
      kubectl:
        manifests:
        - k8s/deployment.yaml
  - name: v2
    deploy:
      kubectl:
        manifests:
        - k8s/deployment-v2.yaml
        - k8s/istio.yaml
